# Basic
title: Masimaro's Blog
subtitle: Masimaro 的个人博客——学习，交流，进步，提高


url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 查看博客

# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: masimaro
    # duoshuo: 
    
# Social
social:
    weibo: https://weibo.com/p/1005052343726384/home?from=page_100505&mod=TAB&is_all=1#place
    github: https://github.com/HaiLateBoy/
    twitter: http://blog.csdn.net/lanuage
    gplus: 101936521088591215836
    mail: liu1793222129@163.com
markdown: kramdown
# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
